# Generated by Django 5.2.17 on 2026-08-12 11:27

import core.fields
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Etablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("HOPITAL", "Hôpital"),
                            ("CLINIQUE", "Clinique"),
                            ("CENTRE", "Centre de kinésithérapie"),
                        ],
                        default="CLINIQUE",
                        max_length=20,
                    ),
                ),
                ("ville", models.CharField(max_length=80)),
                ("adresse", models.CharField(blank=True, max_length=200)),
                ("telephone", models.CharField(blank=True, max_length=40)),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["ville", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("libelle", models.CharField(max_length=80)),
                ("specialite", models.CharField(blank=True, max_length=60)),
                ("ordre", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="RendezVous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=core.models._reference_courte,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("patient_nom", models.CharField(max_length=80)),
                ("patient_prenom", models.CharField(max_length=80)),
                (
                    "patient_telephone",
                    core.fields.EncryptedCharField(blank=True, max_length=255),
                ),
                ("date_rdv", models.DateField()),
                ("heure_rdv", models.TimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRME", "Confirmé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("consentement_donnees", models.BooleanField(default=False)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "etablissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rendez_vous",
                        to="core.etablissement",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rendez_vous",
                        to="core.zone",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="Recu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=30, unique=True)),
                (
                    "montant",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                ("devise", models.CharField(default="FCFA", max_length=8)),
                ("fichier", models.FileField(upload_to="recus/")),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "rendez_vous",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recu",
                        to="core.rendezvous",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
        migrations.AddConstraint(
            model_name="rendezvous",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "ANNULE"), _negated=True),
                fields=("etablissement", "date_rdv", "heure_rdv"),
                name="creneau_unique_par_etablissement",
            ),
        ),
    ]
